\documentclass{article}
%\VignettePackage{outbreaker}
%\VignetteIndexEntry{Handling disease outbreak data}
%\VignetteEngine{knitr}

\usepackage{graphicx}
\usepackage[colorlinks=true,urlcolor=blue]{hyperref}
\usepackage{array}
\usepackage{color}
\usepackage{geometry}
\geometry{verbose,tmargin=3cm,bmargin=3cm,lmargin=3cm,rmargin=3cm}

\usepackage[utf8]{inputenc} % for UTF-8/single quotes from sQuote()
\newcommand{\code}[1]{{{\tt #1}}}
\title{An introduction to \textit{outbreaker} \Sexpr{packageDescription("outbreaker", fields = "Version")}}
\author{Thibaut Jombart}
\date{\today}




\sloppy
\hyphenpenalty 10000


\begin{document}


<<eval=TRUE,echo=FALSE,results='hide'>>=
library(knitr)
opts_chunk$set(fig.path='figs/', fig.keep='last', dev='pdf', fig.width=7, fig.height=7,
               tidy=FALSE, warning=FALSE, fig.show='asis', fig.align='center', cache=FALSE,
               out.width=".6\\textwidth")
options(width=80)
@

\color{black}

\maketitle

\begin{abstract}
  This vignette introduces the main functionalities of \textit{outbreaker}, a package implementing a
  model for disease outbreak reconstruction using epidemiological data and pathogen genome sequences.
\end{abstract}

\newpage

\tableofcontents





\end{document}
